apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connector
  namespace: bank-api
data:
  # kv format
  DB_URL: "jdbc:postgresql://postgresql-primary.postgresql.svc.cluster.local:5432/bank"
  DB_USER: "postgres"
  DB_PASS: "NtifHwnrfQ"
